[package]
name = "nft-bridge"
version = "0.1.0"
edition = "2018"
description = "Wormhole NFT bridge"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cosmwasm-std = "1.0.0"
cosmwasm-storage = { version = "1.0.0" }
cw721 = { path = "../../packages/cw721" }
cw721-base = { path = "../cw721-base", version = "0.10.0", features = ["library"] }
cw721-wrapped = { path = "../cw721-wrapped", features = ["library"] }
hex = "0.4.2"
schemars = "0.8.10"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
sha3 = { version = "0.10.1", default-features = false }
wormhole-bridge-paloma = { path = "../wormhole", features = ["library"] }

[dev-dependencies]
serde_json = "1.0"
lazy_static = "1.4.0"
